---
vault_app_root: /opt/vault
vault_app_user: vault
vault_service_name: vault-api
vault_api_port: 8080
vault_keep_releases: 5

vault_admin_domain: admin.example.com
vault_guest_domain: guest.example.com
vault_api_domain: api.example.com

vault_build_goos: linux
vault_build_goarch: amd64
vault_build_cgo_enabled: "1"

vault_panel_password: "change-this-before-first-deploy"
